### ISSUE TITLE
Show password icon not working on Passphrase confirm page

### ISSUE THREAD

**Issue by saurabh73** [osvauld/web-client#191]
![image](https://github.com/osvauld/web-client/assets/10613021/5a6128c7-c0ad-48ab-9c39-b465acd71852)

**Comment by tonyantony300** [comment]
Hi @saurabh73 ,

Thanks for opening this issue. Fix is currently available in the development branch and will be shipped with next release, ie, Version 0.1.2 

@Bijoyjoseph96
