### ISSUE TITLE
After account recovery, username is not set

### ISSUE THREAD

**Issue by saurabh73** [osvauld/web-client#192]
![image](https://github.com/osvauld/web-client/assets/10613021/bb2f89ae-0dca-4a08-8e0b-e7b288dff39d)

**Comment by tonyantony300** [comment]
Hi @saurabh73 ,

Thanks for opening this issue. Fix is currently available in the development branch and will be shipped with next release, ie, Version 0.1.2 

@Bijoyjoseph96
